encoding: UTF-8
title:            天下
description:      书不如思贵，意不可言传
# put your disqus here
disqus_shortname: 
reading_time:     false  # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://blog.genesino.com
img_url: http://blog.genesino.com/images

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'About'
    url: '/about'

  - title: 'Tags'
    url: '/tags'
  - title: 'Categories'
    url: '/categories'

  - title: 'Favorites'
    url: '#'
    submenu:
      - title: 'Code Highlighter'
        url: '/intro/code-highlighting-post/'
      - title: 'Sample Post'
        url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           CHENTONG
  site:           http://blog.genesino.com
  avatar:         images/avatar.jpg
  bio:            "积微，月不胜日，时不胜月，岁不胜时。凡人好敖慢小事，大事至，然后兴之务之。如是，则常不胜夫敦比于小事者矣！何也？小事之至也数，其悬日也博，其为积也大。大事之至也希，其悬日也浅，其为积也小。故善日者王，善时者霸，补漏者危，大荒者亡！故，王者敬日，霸者敬时，仅存之国危而后戚之。亡国至亡而后知亡，至死而后知死，亡国之祸败，不可胜悔也。霸者之善著也，可以时托也。王者之功名，不可胜日志也。财物货宝以大为重，政教功名者反是，能积微者速成。诗曰：德如毛，民鲜能克举之。此之谓也。"
  email:          chentong_biology@163.com
  # Twitter nick for use in Twitter cards and follow button.
  #twitter: aron_bordin # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  #github: aron-bordin

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
#twitter: 

# Social networking links used in author block underneath posts. Update and remove as you like.
#social:
#  - title: "github"
#    url: "https://github.com/aron-bordin"
#  - title: "linkedin"
#    url: "https://br.linkedin.com/in/aronbordin"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Hong_Kong
locale:      en_US
future:      true
highlighter: rouge
#highlighter: pygments
markdown:    kramdown
#markdown:    redcarpet
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:year/:month/:title/

# Amount of post to show on home page
paginate: 5

# if true, shows the floatting share buttons
float_share: false

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
